language: cpp
compiler:
  - gcc
  - clang
python:
  - "2.7"
install:
  - if [ "$CXX" "==" "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" "==" "g++" ]; then sudo apt-get update; fi
  - if [ "$CXX" "==" "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "$CXX" "==" "g++" ]; then export CC=gcc-4.8; fi
  - if [ "$CXX" "==" "g++" ]; then export CXX=g++-4.8; fi
  - if [ "$CXX" "==" "clang++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" "==" "clang++" ]; then sudo add-apt-repository -y "deb http://llvm.org/apt/raring/ llvm-toolchain-raring main"; fi
  - if [ "$CXX" "==" "clang++" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -; fi
  - if [ "$CXX" "==" "clang++" ]; then sudo apt-get update; fi
  - if [ "$CXX" "==" "clang++" ]; then sudo apt-get install clang-3.4; fi
  - if [ "$CXX" "==" "clang++" ]; then /usr/bin/clang --version; fi
  - if [ "$CXX" "==" "clang++" ]; then whereis clang; fi
  - if [ "$CXX" "==" "clang++" ]; then which clang; fi
  - if [ "$CXX" "==" "clang++" ]; then export CC=/usr/bin/clang; fi
  - if [ "$CXX" "==" "clang++" ]; then export CXX=/usr/bin/clang++; fi
  - $CC --version
  - $CXX --version
  - ./get_deps_ubuntu.sh
  - mkdir build
  - cd build
  - cmake ..
script:
  - make lint
  - make test
  - cd ..
  - bash run_doxygen.sh
