language: cpp
compiler:
  - gcc
  - clang
python:
  - "2.7"
install:
  - if [ "$CXX" "==" "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" "==" "g++" ]; then sudo apt-get update; fi
  - if [ "$CXX" "==" "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "$CXX" "==" "g++" ]; then export CC=gcc-4.8; fi
  - if [ "$CXX" "==" "g++" ]; then export CXX=g++-4.8; fi
  - $CC --version
  - $CXX --version
  - ./get_deps_ubuntu.sh
  - mkdir build
  - cd build
  - cmake ..
script:
  - make lint
  - make test
  - cd ..
  - bash run_doxygen.sh
